declaration/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('subs/', include('subs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.register_guest, name='register_guest'),
    path('thanks', views.thank_you, name='thank_you'),
]

subs/models.py
from django.db import models
from django.utils import timezone
import datetime


class Sub(models.Model):
    BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

    date_format = '%d-%m-%Y %H:%M:%S'

    name = models.CharField(max_length=255)
    mobile_number = models.CharField(max_length=255, default='')
    company = models.CharField(max_length=255, default='')
    purpose = models.TextField(default='')
    temperature = models.CharField(max_length=255, default='')
    time_scanned = models.CharField(max_length=255, default='', blank=False)
    visit_pass_number = models.CharField(max_length=255, default='')

    is_quarantined = models.BooleanField(choices=BOOL_CHOICES, default=False)
    is_contacted = models.BooleanField(choices=BOOL_CHOICES, default=False)
    has_travelled = models.BooleanField(choices=BOOL_CHOICES, default=False)
    is_unwell = models.BooleanField(choices=BOOL_CHOICES, default=False)

    reg_date = models.DateField(default=timezone.now)
    acknowledge = models.BooleanField(choices=BOOL_CHOICES, default=True)

    def get_full_name(self):
        """Get full name of the user"""
        return self.name

    def get_short_name(self):
        """Get short name of the user"""
        return self.name

    def __str__(self):
        """Render string in the admin"""
        return self.name + ' - ' + self.mobile_number

subs/forms.py
from django import forms
from .models import Sub


class SubForm(forms.ModelForm):

    class Meta:
        model = Sub
        fields = ('name', 'mobile_number', 'company', 'visit_pass_number', 'purpose', 'temperature', 'time_scanned', 'is_quarantined', 'is_contacted', 'has_travelled', 'is_unwell', 'reg_date', 'acknowledge')

subs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import SubForm
from django.contrib import messages



# Registering a guest
def register_guest(request):
    if request.method == 'POST':
        form = SubForm(request.POST)
        if form.is_valid():
            # cleaned = form.cleaned_data
            form.save()
            # messages.success(request, 'Guest is registered successfully!')
            return redirect('thank_you')
    else:
        form = SubForm()

    return render(request, 'register_guest.html', {'form': form})


def thank_you(request):
    return render(request, 'thank_you.html')

subs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>CTC Health Declaration Form</title>
  <meta http-equiv="cache-control" content="public" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" type="text/css" />
  <link rel="stylesheet" href="{% static 'subs/css/main.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">
        <img src="/media/ctc-logo-declaration.png" />
      </span>
    </nav>
    {% block content %}
    {% endblock content %}
    {% block thanks %}
    {% endblock thanks %}
  </div>
</body>

subs/templates/register_guest.html
{% extends 'base.html' %}
{% block content %}
  <!-- Form Sample -->
  <form id="regForm" action="" method="post" enctype="multipart/form-data" autocomplete="on">
    {% csrf_token %}
    <h2>CTC Health Declartion Form</h2>
    <div class="tab">
      <h3>Personal Information</h3>
      <p>
        <strong>Full Name:</strong><span id="manda">&nbsp;*</span><br />
        <input type="text" name="name" maxlength="255" required id="id_name" autocomplete="name">
      </p>
      <p>
        <strong>Mobile Number:</strong><span id="manda">&nbsp;*</span><br />
        <input type="text" name="mobile_number" maxlength="255" required id="id_mobile_number" autocomplete="mobile_number">
      </p>
      <p>
        <strong>Name of the Company:</strong> (required for visitors, N/A for staff)<span id="manda">&nbsp;*</span><br />
        <input type="text" name="company" maxlength="255" id="id_company" autocomplete="company" value="N/A">
      </p>
      <p>
        <strong>Please indicate purpose of visit to the office:</strong> (required for visitors, N/A for staff)<span id="manda">&nbsp;*</span><br />
        <input type="text" name="purpose" maxlength="255" id="id_purpose" autocomplete="purpose" value="N/A">
      </p>
      <p>
        <strong>Visitor's Pass Number:</strong> (required for visitors, N/A for staff)<span id="manda">&nbsp;*</span><br />
        <input type="text" name="visit_pass_number" maxlength="255" id="id_visit_pass_number" autocomplete="visit_pass_number" value="N/A">
      </p>
      <p>
        <strong>Temperature Recorded:</strong><span id="manda">&nbsp;*</span><br />
        (Kindly note that if you are unwell and/ or if your temperature is 37.4 Degree Celsius and above, you will be refused entry to CTC workplace premises.)<br />
        {{ form.temperature }}
      </p>
      <p>
        <strong>Time of Temperature Screening:</strong><span id="manda">&nbsp;*</span><br />
        <input type="time" name="time_scanned" maxlength="255" id="id_time_scanned" autocomplete="time_scanned">
      </p>
    </div>
    <div class="tab">
      <h3>Health Well-being and Recent Travel History</h3><br />
      <p>
        <strong>Are you currently serving Quarantine Order (QO), Leave of Absence (LOA) or Stay-Home Notice (SHN)?</strong><span id="manda">&nbsp;*</span><br /><br />
        {{ form.is_quarantined }}<br /><br />
      </p>
      <p>
        <strong>Within the last 14 days, have you had contact with a COVID-19 confirmed case or suspect case, or a person issued Quarantine Order (QO) / Leave of Absence (LOA) / Stay-Home Notice (SHN)?</strong><span id="manda">&nbsp;*</span><br /><br />
        {{ form.is_contacted }}<br /><br />
      </p>
      <p>
        <strong>Have you travelled to any country outside of Singapore, including but not limited to nearby locations such as Johor Bahru, Batam and Bintan, in the past 14 days?</strong><span id="manda">&nbsp;*</span><br /><br />
        {{ form.has_travelled }}<br /><br />
      </p>
      <p>
        <strong>Are you feeling unwell or having any symptoms such as fever, cough, runny nose, sore throat, breathlessness?</strong><span id="manda">&nbsp;*</span><br /><br />
        {{ form.is_unwell }}<br /><br />
      </p>
    </div>
    <div class="tab">
      <h3>Acknowledgement</h3><br />
      <p>
        <strong>I acknowledge</strong><span id="manda">&nbsp;*</span>&nbsp;{{ form.acknowledge }}
      </p>
      <p>
        <strong>Date:</strong><span id="manda">&nbsp;*</span><br />
        <input type="date" name="reg_date" maxlength="255" required id="id_reg_date" onchange="reFresh()"><br /><br />
      </p>
    </div>
    <div style="overflow:auto;">
      <div style="float:right;">
        <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
        <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
        <input type="submit" id="subBtn" value="Submit">
      </div>
    </div>

    <div style="text-align:center;margin-top:40px;">
      <span class="step"></span>
      <span class="step"></span>
      <span class="step"></span>
    </div>

  </form>

  <!-- End Form Sample-->


  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li id="reg-message-success" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}


  {% load static %}
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  <script src="{% static 'subs/js/registration.js' %}"></script>
  <script src='https://cdn.jsdelivr.net/gh/FThompson/FormPersistence.js@2.0.6/form-persistence.min.js'></script>
  <script>
    let newform = document.getElementById('regForm');
    FormPersistence.persist(newform);
  </script>
  <script>
    $(document).ready(function() {
        $("#id_company").val("N/A");
        $("#id_purpose").val("N/A");
        $("#id_visit_pass_number").val("N/A");
    });

    function reFresh() {
      confirm("Review your sumbmtted Information.");
      window.location.reload();
    }


  </script>
{% endblock %}

subs/templates/thank_you.html
{% extends 'base.html' %}
{% block thanks %}
<h1>Thank you for your submission!</h1>
<img src="/media/check.png" style="width: 100%;" />
{% endblock thanks %}